services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: freshman-pass:latest
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      # - .:/usr/src/app
      - bundle:/usr/local/bundle
      - storage:/usr/local/storage
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: pg_isready -U pass
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=pass
      - POSTGRES_DB=pass
      - POSTGRES_PASSWORD=changeme
      - PGDATA=/data/pgdata
    volumes:
      - pg_data:/data/pgdata

volumes:
  pg_data:
  bundle:
  storage:
