# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6069ec2918dbe7d6ab9dbdd7bb168bc5b4240dcd23c7463ed909700478ed974098127cdf34dc549a4b46d9b1e6ba23d92b8a7bd7c090c00be8310833bf50b70

test:
  secret_key_base: 7e2453e774438e7bd3c32f4e85e1ab3a0eb8a023b91f055239fc63b5cfe0619d9a17f06cbe3e45c712a2a71cf2141f0ac0bb11b18774beb511a9a88ea1dcaf9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
